---
title: "Analiza estymacji VaR w GARCH(1, 1)"
author: "Cezary Moskal"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: "hide"
    css: "style.css"
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
```

```{r Functions}
n <- c(100, 250, 500, 1000, 2500, 5000, 10000)
colors = c('Rozkład Normalny' = '#56B4E9', 'Historyczne' = '#009E73',
           'Cornish-Fisher' = '#CC79A7', 'Prawdziwa Wartość' = 'red')

plot_VaR <- function(data, mod, dis) {
  if (dis == 'std') {
    dist_name = 't-Student'
  }
  else {
    dist_name = 'skew-normal'
  }
  p = data %>%
    filter(model == mod, dist == dis) %>%
    ggplot() +
    geom_hline(aes(color = 'Prawdziwa Wartość', yintercept = 0.05),
               linetype = 'dashed',
               linewidth = 1, key_glyph = draw_key_rect) +
    geom_line(aes(x = n, y = gaussian, color = 'Rozkład Normalny'),
              key_glyph = draw_key_rect) +
    geom_line(aes(x = n, y = historic, color = 'Historyczne'),
              key_glyph = draw_key_rect) +
    geom_line(aes(x = n, y = modified, color = 'Cornish-Fisher'),
              key_glyph = draw_key_rect) +
    ggtitle(label = 'Estymacja VaR w GARCH(1,1)', subtitle = 
            paste0('Zależność od wielkości próby (Model ',
                   mod, ' - ', dist_name, ')')) +
    xlab('Próba') +
    ylab('% Przekroczeń') +
    scale_x_continuous(trans = 'log10', expand = c(0, 0),
                       breaks = n) +
    scale_y_continuous(expand = c(0, 0), limits = c(0, 0.08),
                       breaks = seq(0, 0.1, 0.005),
                       labels = scales::percent) +
    scale_color_manual(values = colors) +
    guides(color = guide_legend('')) +
    theme_bw()
  return(p)
}
```

```{r LoadData}
df <- read.csv('Results/VaR.csv')
```

```{r Student}
plot_VaR(df, 1, 'std')
plot_VaR(df, 2, 'std')
plot_VaR(df, 3, 'std')
```

```{r SkewNormal}
plot_VaR(df, 1, 'snorm')
plot_VaR(df, 2, 'snorm')
plot_VaR(df, 3, 'snorm')
```
