---
title: "Efekt niepoprawnego założenia o warunkowym rozkładzie składnika losowego na estymację GARCH(1,1)"
author: "Cezary Moskal"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: "hide"
    css: "style.css"
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(rugarch)
library(tidyverse)
library(latex2exp)
library(BSDA)
```

```{r Functions}
n <- c(100, 250, 500, 1000, 2500, 5000, 10000)
colors <- c('Estymacje' = 'orange',
            'Średnia' = 'blue', 'Prawdziwa Wartość' = 'red')

garch <- function(mu, omega, alpha, beta, model = 'norm',
                  shape = 0, skew = 0, estimate = 'norm') {
  set.seed(123)
  values <<- list()
  omega_values <<- c()
  alpha_values <<- c()
  beta_values <<- c()
  spec = ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = TRUE,
                                      archm = FALSE, archpow = 1,
                                      arfima = FALSE,
                                      external.regressors = NULL,
                                      archex = FALSE),
                    fixed.pars = list(mu = mu,
                                      omega = omega, alpha1 = alpha,
                                      beta1 = beta, shape = shape, skew = skew),
                    distribution.model = model)
  for (j in n) {
    omega = numeric(100)
    alpha = numeric(100)
    beta = numeric(100)
    for (k in 1:100) {
      fit = NULL
      while (is.null(fit) || convergence(fit) != 0) {
        data = fitted(ugarchpath(spec, j))
        specfit = ugarchspec(mean.model = list(armaOrder = c(0, 0),
                                               include.mean = TRUE,
                                               archm = FALSE, 
                                               archpow = 1, arfima = FALSE,
                                               external.regressors = NULL,
                                               archex = FALSE),
                             fixed.pars = list(shape = shape, skew = skew),
                             distribution.model = estimate)
        fit = ugarchfit(spec = specfit, data = data, solver = 'hybrid')
      }
      omega[k] = coef(fit)[2]
      alpha[k] = coef(fit)[3]
      beta[k] = coef(fit)[4]
    }
    values <<-
      append(values, list(c(mean(mu), mean(omega), mean(alpha), mean(beta))))
    omega_values <<- c(omega_values, omega)
    alpha_values <<- c(alpha_values, alpha)
    beta_values <<- c(beta_values, beta)
  }
  omega_final <<- numeric(7)
  alpha_final <<- numeric(7)
  beta_final <<- numeric(7)
  for (i in 1:7) {
    omega_final[i] <<- values[[i]][2]
    alpha_final[i] <<- values[[i]][3]
    beta_final[i] <<- values[[i]][4]
  }
}

plot_estimates <- function(variable, value, dis, mod, cap, interval) {
  if (variable == 'omega') {
    var1 = omega_values
    var2 = omega_final
    latex = '\\omega'
  }
  else if (variable == 'alpha') {
    var1 = alpha_values
    var2 = alpha_final
    latex = '$\\alpha_1$'
  }
  else {
    var1 = beta_values
    var2 = beta_final
    latex = '$\\beta_1$'
  }
  p = ggplot() +
  geom_jitter(aes(x = rep(n, each = 100), y = var1, color = 'Estymacje'),
              alpha = 0.3, key_glyph = draw_key_rect) +
  geom_hline(aes(color = 'Prawdziwa Wartość', yintercept = value),
             linetype = 'dashed',
             linewidth = 1, key_glyph = draw_key_rect) +
  geom_point(aes(x = n, y = var2, color = 'Średnia'), size = 3,
             key_glyph = draw_key_rect) +
  ggtitle(label = TeX(paste0('Estymator ', latex, ' w GARCH(1,1)')), subtitle = 
          paste0('Zależność od wielkości próby (Model ', mod, ' - ', dis, ')')) +
  xlab('Próba') +
  ylab(TeX(paste0('Wartość ', latex))) +
  scale_x_continuous(trans = 'log10', expand = c(0, 0), 
                     breaks = n) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, cap),
                     breaks = seq(0, cap, interval)) +
  scale_color_manual(values = colors) +
  guides(color = guide_legend('')) +
  theme_bw()
  return(p)
}
```

$$r_t=\mu+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t$$
$$\sigma_t^2=\omega+\alpha_1\varepsilon_{t-1}^2+\beta_1\sigma_{t-1}^2$$

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t,\epsilon_t\sim{IN(0,1)}$$
$$\sigma_t^2=1+0.4\varepsilon_{t-1}^2+0.5\sigma_{t-1}^2$$

```{r Normal_Model1}
garch(5, 1, 0.4, 0.5)
plot_estimates('omega', 1, 'norm', '1', 5, 0.5)
plot_estimates('alpha', 0.4, 'norm', '1', 1, 0.1)
plot_estimates('beta', 0.5, 'norm', '1', 1, 0.1)
```

```{r Normal_Model1_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(omega_values[101:200], mu = 1, sigma.x = sd(omega_values[101:200]))
z.test(alpha_values[1:100], mu = 0.4, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.5, sigma.x = sd(beta_values[1:100]))
z.test(beta_values[101:200], mu = 0.5, sigma.x = sd(beta_values[101:200]))
```

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t,\epsilon_t\sim{IN(0,1)}$$
$$\sigma_t^2=1+0.8\varepsilon_{t-1}^2+0.1\sigma_{t-1}^2$$

```{r Normal_Model2}
garch(5, 1, 0.8, 0.1)
plot_estimates('omega', 1, 'norm', '2', 2.5, 0.5)
plot_estimates('alpha', 0.8, 'norm', '2', 1, 0.1)
plot_estimates('beta', 0.1, 'norm', '2', 1, 0.1)
```

```{r Normal_Model2_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(alpha_values[1:100], mu = 0.8, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.1, sigma.x = sd(beta_values[1:100]))
```

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t,\epsilon_t\sim{IN(0,1)}$$
$$\sigma_t^2=1+0.1\varepsilon_{t-1}^2+0.8\sigma_{t-1}^2$$

```{r Normal_Model3}
garch(5, 1, 0.1, 0.8)
plot_estimates('omega', 1, 'norm', '3', 3, 0.5)
plot_estimates('alpha', 0.1, 'norm', '3', 1, 0.1)
plot_estimates('beta', 0.8, 'norm', '3', 1, 0.1)
```

```{r Normal_Model3_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(omega_values[301:400], mu = 1, sigma.x = sd(omega_values[301:400]))
z.test(alpha_values[1:100], mu = 0.1, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.8, sigma.x = sd(beta_values[1:100]))
```

$$K=\frac{6}{\nu-4} + 3=9$$

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t$$
$$\sigma_t^2=1+0.4\varepsilon_{t-1}^2+0.5\sigma_{t-1}^2$$

```{r Student_Model1_Err}
garch(5, 1, 0.4, 0.5, 'std', 5)
plot_estimates('omega', 1, 't-student (err)', '1', 5, 0.5)
plot_estimates('alpha', 0.4, 't-student (err)', '1', 1, 0.1)
plot_estimates('beta', 0.5, 't-student (err)', '1', 1, 0.1)
```

```{r Student_Model1_Tests_Err}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(alpha_values[1:100], mu = 0.4, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.5, sigma.x = sd(beta_values[1:100]))
```

```{r Student_Model1}
garch(5, 1, 0.4, 0.5, 'std', 5, estimate = 'std')
plot_estimates('omega', 1, 't-student', '1', 5, 0.5)
plot_estimates('alpha', 0.4, 't-student', '1', 1, 0.1)
plot_estimates('beta', 0.5, 't-student', '1', 1, 0.1)
```

```{r Student_Model1_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(alpha_values[1:100], mu = 0.4, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.5, sigma.x = sd(beta_values[1:100]))
```

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t$$
$$\sigma_t^2=1+0.8\varepsilon_{t-1}^2+0.1\sigma_{t-1}^2$$

```{r Student_Model2_Err}
garch(5, 1, 0.8, 0.1, 'std', 5)
plot_estimates('omega', 1, 't-student (err)', '2', 2.5, 0.5)
plot_estimates('alpha', 0.8, 't-student (err)', '2', 1, 0.1)
plot_estimates('beta', 0.1, 't-student (err)', '2', 1, 0.1)
```

```{r Student_Model2_Tests_Err}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(alpha_values[1:100], mu = 0.8, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.1, sigma.x = sd(beta_values[1:100]))
```

```{r Student_Model2}
garch(5, 1, 0.8, 0.1, 'std', 5, estimate = 'std')
plot_estimates('omega', 1, 't-student', '2', 2.5, 0.5)
plot_estimates('alpha', 0.8, 't-student', '2', 1, 0.1)
plot_estimates('beta', 0.1, 't-student', '2', 1, 0.1)
```

```{r Student_Model2_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(alpha_values[1:100], mu = 0.8, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.1, sigma.x = sd(beta_values[1:100]))
```

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t$$
$$\sigma_t^2=1+0.1\varepsilon_{t-1}^2+0.8\sigma_{t-1}^2$$

```{r Student_Model3_Err}
garch(5, 1, 0.1, 0.8, 'std', 5)
plot_estimates('omega', 1, 't-student (err)', '3', 11, 1)
plot_estimates('alpha', 0.1, 't-student (err)', '3', 1, 0.1)
plot_estimates('beta', 0.8, 't-student (err)', '3', 1, 0.1)
```

```{r Student_Model3_Tests_Err}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(omega_values[101:200], mu = 1, sigma.x = sd(omega_values[101:200]))
z.test(alpha_values[1:100], mu = 0.1, sigma.x = sd(alpha_values[1:100]))
z.test(alpha_values[101:200], mu = 0.1, sigma.x = sd(alpha_values[101:200]))
z.test(beta_values[1:100], mu = 0.8, sigma.x = sd(beta_values[1:100]))
z.test(beta_values[101:200], mu = 0.8, sigma.x = sd(beta_values[101:200]))
```

```{r Student_Model3}
garch(5, 1, 0.1, 0.8, 'std', 5, estimate = 'std')
plot_estimates('omega', 1, 't-student', '3', 11, 1)
plot_estimates('alpha', 0.1, 't-student', '3', 1, 0.1)
plot_estimates('beta', 0.8, 't-student', '3', 1, 0.1)
```

```{r Student_Model3_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(omega_values[101:200], mu = 1, sigma.x = sd(omega_values[101:200]))
z.test(alpha_values[1:100], mu = 0.1, sigma.x = sd(alpha_values[1:100]))
z.test(alpha_values[101:200], mu = 0.1, sigma.x = sd(alpha_values[101:200]))
z.test(beta_values[1:100], mu = 0.8, sigma.x = sd(beta_values[1:100]))
z.test(beta_values[101:200], mu = 0.8, sigma.x = sd(beta_values[101:200]))
```

$$f(x)=2\phi(x)\Phi(4x)$$

$$\delta=\frac{4}{\sqrt{17}}$$

$$A=\frac{4-\pi}{2}\frac{(\delta\sqrt{2/\pi})^3}{(1-2\delta^2/\pi)^{3/2}}\approx0.784427$$

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t$$
$$\sigma_t^2=1+0.4\varepsilon_{t-1}^2+0.5\sigma_{t-1}^2$$

```{r SkewNormal_Model1_Err}
garch(5, 1, 0.4, 0.5, 'snorm', skew = 4)
plot_estimates('omega', 1, 'skew-normal (err)', '1', 5, 0.5)
plot_estimates('alpha', 0.4, 'skew-normal (err)', '1', 1, 0.1)
plot_estimates('beta', 0.5, 'skew-normal (err)', '1', 1, 0.1)
```

```{r SkewNormal_Model1_Tests_Err}
z.test(omega_values[201:300], mu = 1, sigma.x = sd(omega_values[201:300]))
z.test(alpha_values[1:100], mu = 0.4, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.5, sigma.x = sd(beta_values[1:100]))
```

```{r SkewNormal_Model1}
garch(5, 1, 0.4, 0.5, 'snorm', skew = 4, estimate = 'snorm')
plot_estimates('omega', 1, 'skew-normal', '1', 5, 0.5)
plot_estimates('alpha', 0.4, 'skew-normal', '1', 1, 0.1)
plot_estimates('beta', 0.5, 'skew-normal', '1', 1, 0.1)
```

```{r SkewNormal_Model1_Tests}
z.test(omega_values[201:300], mu = 1, sigma.x = sd(omega_values[201:300]))
z.test(alpha_values[1:100], mu = 0.4, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.5, sigma.x = sd(beta_values[1:100]))
```

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t$$
$$\sigma_t^2=1+0.8\varepsilon_{t-1}^2+0.1\sigma_{t-1}^2$$

```{r SkewNormal_Model2_Err}
garch(5, 1, 0.8, 0.1, 'snorm', skew = 4)
plot_estimates('omega', 1, 'skew-normal (err)', '2', 2.5, 0.5)
plot_estimates('alpha', 0.8, 'skew-normal (err)', '2', 1, 0.1)
plot_estimates('beta', 0.1, 'skew-normal (err)', '2', 1, 0.1)
```

```{r SkewNormal_Model2_Tests_Err}
z.test(omega_values[201:300], mu = 1, sigma.x = sd(omega_values[201:300]))
z.test(alpha_values[1:100], mu = 0.8, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.1, sigma.x = sd(beta_values[1:100]))
```

```{r SkewNormal_Model2}
garch(5, 1, 0.8, 0.1, 'snorm', skew = 4, estimate = 'snorm')
plot_estimates('omega', 1, 'skew-normal', '2', 2.5, 0.5)
plot_estimates('alpha', 0.8, 'skew-normal', '2', 1, 0.1)
plot_estimates('beta', 0.1, 'skew-normal', '2', 1, 0.1)
```

```{r SkewNormal_Model2_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(alpha_values[1:100], mu = 0.8, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.1, sigma.x = sd(beta_values[1:100]))
```

$$r_t=5+\varepsilon_t$$
$$\varepsilon_t=\epsilon_t\sigma_t$$
$$\sigma_t^2=1+0.1\varepsilon_{t-1}^2+0.8\sigma_{t-1}^2$$

```{r SkewNormal_Model3_Err}
garch(5, 1, 0.1, 0.8, 'snorm', skew = 4)
plot_estimates('omega', 1, 'skew-normal (err)', '3', 10, 1)
plot_estimates('alpha', 0.1, 'skew-normal (err)', '3', 1, 0.1)
plot_estimates('beta', 0.8, 'skew-normal (err)', '3', 1, 0.1)
```

```{r SkewNormal_Model3_Tests_Err}
z.test(omega_values[201:300], mu = 1, sigma.x = sd(omega_values[201:300]))
z.test(alpha_values[1:100], mu = 0.1, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.8, sigma.x = sd(beta_values[1:100]))
```

```{r SkewNormal_Model3}
garch(5, 1, 0.1, 0.8, 'snorm', skew = 4, estimate = 'snorm')
plot_estimates('omega', 1, 'skew-normal', '3', 10, 1)
plot_estimates('alpha', 0.1, 'skew-normal', '3', 1, 0.1)
plot_estimates('beta', 0.8, 'skew-normal', '3', 1, 0.1)
```

```{r SkewNormal_Model3_Tests}
z.test(omega_values[1:100], mu = 1, sigma.x = sd(omega_values[1:100]))
z.test(alpha_values[1:100], mu = 0.1, sigma.x = sd(alpha_values[1:100]))
z.test(beta_values[1:100], mu = 0.8, sigma.x = sd(beta_values[1:100]))
```
