---
title: "Symulacja GARCH(1, 1)"
author: "Cezary Moskal"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: "hide"
    css: "style.css"
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rugarch)
library(tidyverse)
library(latex2exp)
```

$$a_t=\epsilon_t\sigma_t,\epsilon_t\sim{IN(0,1)}$$
$$\sigma_t^2=1+0.4a_{t-1}^2+0.5\sigma_{t-1}^2$$

```{r Plot}
set.seed(1)
spec <- ugarchspec(mean.model = list(armaOrder = c(0, 0), include.mean = FALSE,
                                    archm = FALSE, archpow = 1,
                                    arfima = FALSE,
                                    external.regressors = NULL,
                                    archex = FALSE),
                  fixed.pars = list(omega = 1, alpha1 = 0.4,
                                    beta1 = 0.5))
data <- fitted(ugarchpath(spec, 1000))

ggplot() +
  geom_line(aes(x = 1:1000, y = data)) +
  ggtitle('Symulacja GARCH(1, 1)', subtitle = 'Model 1 - norm') +
  labs(x = 't',
       y = TeX('$a_t$')) +
  scale_x_continuous(expand = c(0.01, 0), breaks = seq(0, 1000, 100)) +
  scale_y_continuous(expand = c(0.01, 0), breaks = seq(-20, 20, 4)) +
  theme_bw()
```
